[package]
name = "pokedle_core"
version = "0.1.0"
edition = "2021"
authors = ["Baduit"]

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
chrono = "0.4.31"